### ISSUE TITLE
Trouble on /dev/input system

### ISSUE THREAD

**Issue by DriverLin** [BlissRoms-x86/manifest#41]
I`m using a script: [main.py](https://github.com/DriverLin/Exclusive_mode_mapper/blob/master/src/pythonVer/main.py) on termux to write data to /dev/input/eventX to send touchevent  to system . the script works fine on phone but not work on bliss os . I can see the out put using getevent cmd , but nothing happend on system.

**Comment by electrikjesus** [comment]
I can look into it this weekend

**Comment by hmtheboy154** [comment]
From what I saw on /dev/input/*, I will make a guess here and I hope that's the thing you are looking for
/dev/input/* contain the input events of your hardware (I said /dev/input/* instead of /dev/input/event* because mouse have a separate /dev/input/mouse* and gamepad is /dev/input/js*). 
On phone you can easily hijack /dev/input/event* because you have a touchscreen and the driver on the kernel, meanwhile on PC there is no touchscreen so you basically can't do anything. (There's tablet PC not everyone afford that). There is no touchscreen event available because.......... you don't have a touchscreen. 

So what you should do right now is to find a "virtual touchscreen driver for linux" just for hijacking into that driver and mapping, or make one by yourself.  Maybe something like this : https://github.com/vi/virtual_touchscreen

I hope this can help you, also I wish you can success since I really want a good keymapping for a while now, even if it need root level to run.

**Comment by DriverLin** [comment]
> From what I saw on `/dev/input/*` , I will make a guess here and I hope that's the thing you are looking for `/dev/input/*` contain the input events of your hardware (I said `/dev/input/*` instead of `/dev/input/event*` because mouse have a separate `/dev/input/mouse*` and gamepad is `/dev/input/js*`). On phone you can easily hijack `/dev/input/event*` and control because you have a touchscreen and the driver on the kernel, meanwhile on PC there is no touchscreen so you basically can't do anything. (There's tablet PC but not everyone use that). There is no touch event available because.......... you don't have a touchscreen.
> 
> So what you should do right now is to find a "virtual touchscreen driver for linux" just for hijacking into that driver and mapping, or make one by yourself. Maybe something like this : https://github.com/vi/virtual_touchscreen
> 
> I hope this can help you, also I wish you can success since I really want a good keymapping for a while now, even if it need root level to run.

but ,if you have a laptop, you can try two finger stause

> From what I saw on `/dev/input/*` , I will make a guess here and I hope that's the thing you are looking for `/dev/input/*` contain the input events of your hardware (I said `/dev/input/*` instead of `/dev/input/event*` because mouse have a separate `/dev/input/mouse*` and gamepad is `/dev/input/js*`). On phone you can easily hijack `/dev/input/event*` and control because you have a touchscreen and the driver on the kernel, meanwhile on PC there is no touchscreen so you basically can't do anything. (There's tablet PC but not everyone use that). There is no touch event available because.......... you don't have a touchscreen.
> 
> So what you should do right now is to find a "virtual touchscreen driver for linux" just for hijacking into that driver and mapping, or make one by yourself. Maybe something like this : https://github.com/vi/virtual_touchscreen
> 
> I hope this can help you, also I wish you can success since I really want a good keymapping for a while now, even if it need root level to run.

I found that the two-finger swipe gesture from touchpad can be detected as a touch screen operation, but i have no idea how this work.😥 I think it is a virtural device created by system but write data into it not work at all.

**Comment by MrMiy4mo** [comment]
We can use ".idc" file for configuring some input devices.
It is possible to setup touchpad as a touchscreen, i think this might work for you.

**Comment by hmtheboy154** [comment]
> We can use ".idc" file for configuring some input devices. It is possible to setup touchpad as a touchscreen, i think this might work for you.

I hope Touchpad can be a good solution tho, but we still solved the laptop side (or some Desktop with Touchpad on their keyboard).

**Comment by DriverLin** [comment]
[u_input_interface.go](https://github.com/DriverLin/go-touch-mapper/blob/main/u_input_interface.go#L36)
virtual touchScreen works fine, my problem solved.
